"""Official Student List / Nominal Roll PDF generator using ReportLab.

Generates an institutional PDF with:
- Visvesvaraya College of Engineering & Technology header with logo
- Department of CSE (Data Science)
- Document metadata (Semester/Year, Batch, Total Students, Date, Generated By)
- Clean tabular student list (S.No, Roll No, Name, Year & Batch, Email, Phone)
- Bottom footer with NextGen SMS branding and dynamic 'Page X of Y' numbering.
"""

from __future__ import annotations

import io
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    Image as RLImage,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# Look for VCET emblem logo in standard asset paths
POSSIBLE_LOGO_PATHS = [
    Path(__file__).parent.parent.parent / "webapp" / "static" / "img" / "vcet_logo.png",
    Path(__file__).parent.parent.parent / "webapp" / "static" / "img" / "logo.png",
    Path(__file__).parent.parent.parent / "frontend" / "public" / "logo.png",
    Path(__file__).parent.parent.parent / "frontend" / "public" / "logo.jpg",
]


def _get_logo_path() -> Path | None:
    for p in POSSIBLE_LOGO_PATHS:
        if p.exists():
            return p
    return None


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas for dynamic total page count (Page X of Y) and footer."""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def showPage(self) -> None:
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_footer(num_pages)
            super().showPage()
        super().save()

    def draw_footer(self, page_count: int) -> None:
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#334155"))

        # Footer divider line
        self.setStrokeColor(colors.HexColor("#1e293b"))
        self.setLineWidth(0.6)
        self.line(14 * mm, 14 * mm, A4[0] - 14 * mm, 14 * mm)

        # Center branding text
        footer_text = "Generated by NextGen SMS — Student Management System"
        self.drawCentredString(A4[0] / 2.0, 9 * mm, footer_text)

        # Page X of Y on right
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(A4[0] - 14 * mm, 9 * mm, page_text)
        self.restoreState()


def build_students_list_pdf(students: list[dict[str, Any]], meta: dict[str, Any]) -> bytes:
    """Builds an official Student List PDF and returns the PDF bytes.

    meta keys:
      - semester_name: str (e.g. '4th Semester (2024-2025)' or 'II Year - II Semester')
      - batch: str (e.g. '2024-2028' or '2024-2028 Batch')
      - total_students: int
      - generated_on: str (e.g. '24-08-2026 11:45 AM')
      - generated_by: str (e.g. 'NextGen SMS' or username)
      - department: str (default 'CSE (DATA SCIENCE)')
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        topMargin=12 * mm,
        bottomMargin=18 * mm,
        leftMargin=14 * mm,
        rightMargin=14 * mm,
    )
    story: list[Any] = []

    # Typography styles
    styles = getSampleStyleSheet()

    header_title_style = ParagraphStyle(
        "HeaderTitle",
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#0f172a"),
    )
    header_sub_style = ParagraphStyle(
        "HeaderSub",
        alignment=TA_CENTER,
        fontName="Helvetica",
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor("#334155"),
    )
    header_dept_style = ParagraphStyle(
        "HeaderDept",
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=2,
    )
    doc_title_style = ParagraphStyle(
        "DocTitle",
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#000000"),
        spaceBefore=6,
        spaceAfter=6,
    )

    # ── Institution Header Block with Logo ──
    logo_path = _get_logo_path()
    logo_img = None
    if logo_path:
        try:
            logo_img = RLImage(str(logo_path), width=20 * mm, height=18 * mm)
        except Exception:
            logo_img = None

    header_text_flowables = [
        Paragraph("<b>Visvesvaraya College of Engineering &amp; Technology</b>", header_title_style),
        Paragraph("An Autonomous Institution &middot; Affiliated to JNTU, Hyderabad", header_sub_style),
        Paragraph("Bongloor X Road, Mangalpally (V), Ibrahimpatnam (M), Hyderabad-501510", header_sub_style),
        Paragraph("<b>DEPARTMENT OF CSE (DATA SCIENCE)</b>", header_dept_style),
    ]

    if logo_img:
        header_table = Table(
            [[logo_img, header_text_flowables]],
            colWidths=[24 * mm, 158 * mm],
        )
        header_table.setStyle(
            TableStyle([
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ALIGN", (0, 0), (0, 0), "CENTER"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ])
        )
        story.append(header_table)
    else:
        for f in header_text_flowables:
            story.append(f)

    # Horizontal divider rule
    story.append(Spacer(1, 3))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0f172a"), spaceAfter=6, spaceBefore=2))

    # Document Title
    story.append(Paragraph("STUDENT LIST", doc_title_style))

    # ── Metadata Block (Two-column format) ──
    meta_label_style = ParagraphStyle(
        "MetaLabel",
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#0f172a"),
    )
    meta_val_style = ParagraphStyle(
        "MetaVal",
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#1e293b"),
    )

    semester_display = meta.get("semester_name") or "All Semesters"
    batch_display = meta.get("batch") or "All Batches"
    total_count = meta.get("total_students", len(students))
    generated_on = meta.get("generated_on") or ""
    generated_by = meta.get("generated_by") or "NextGen SMS"

    meta_data = [
        [
            Paragraph("<b>Semester / Year</b>", meta_label_style),
            Paragraph(f": &nbsp;{semester_display}", meta_val_style),
            Paragraph("<b>Generated On</b>", meta_label_style),
            Paragraph(f": &nbsp;{generated_on}", meta_val_style),
        ],
        [
            Paragraph("<b>Batch</b>", meta_label_style),
            Paragraph(f": &nbsp;{batch_display}", meta_val_style),
            Paragraph("<b>Generated By</b>", meta_label_style),
            Paragraph(f": &nbsp;{generated_by}", meta_val_style),
        ],
        [
            Paragraph("<b>Total Students</b>", meta_label_style),
            Paragraph(f": &nbsp;<b>{total_count}</b>", meta_val_style),
            Paragraph("", meta_label_style),
            Paragraph("", meta_val_style),
        ],
    ]

    meta_table = Table(
        meta_data,
        colWidths=[26 * mm, 65 * mm, 26 * mm, 65 * mm],
    )
    meta_table.setStyle(
        TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 1.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ])
    )
    story.append(meta_table)
    story.append(Spacer(1, 8))

    # ── Table Data (S.No, Roll No, Name, Year & Batch, Email, Phone) ──
    cell_header_style = ParagraphStyle(
        "TH",
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#0f172a"),
    )
    cell_sno_style = ParagraphStyle(
        "TD_SNo",
        alignment=TA_CENTER,
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#1e293b"),
    )
    cell_roll_style = ParagraphStyle(
        "TD_Roll",
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#0f172a"),
    )
    cell_name_style = ParagraphStyle(
        "TD_Name",
        alignment=TA_LEFT,
        fontName="Helvetica",
        fontSize=8,
        leading=10.5,
        textColor=colors.HexColor("#0f172a"),
    )
    cell_batch_style = ParagraphStyle(
        "TD_Batch",
        alignment=TA_CENTER,
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#334155"),
    )
    cell_email_style = ParagraphStyle(
        "TD_Email",
        alignment=TA_LEFT,
        fontName="Helvetica",
        fontSize=7.5,
        leading=9.5,
        textColor=colors.HexColor("#1e293b"),
    )
    cell_phone_style = ParagraphStyle(
        "TD_Phone",
        alignment=TA_CENTER,
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#1e293b"),
    )

    table_data = [
        [
            Paragraph("<b>S.No</b>", cell_header_style),
            Paragraph("<b>Roll No</b>", cell_header_style),
            Paragraph("<b>Name</b>", cell_header_style),
            Paragraph("<b>Year &amp; Batch</b>", cell_header_style),
            Paragraph("<b>Email</b>", cell_header_style),
            Paragraph("<b>Phone</b>", cell_header_style),
        ]
    ]

    for idx, student in enumerate(students, start=1):
        s_roll = str(student.get("roll_no") or "").upper()
        s_name = str(student.get("name") or "")
        s_batch = str(student.get("batch") or student.get("year_of_study") or "—")
        s_email = str(student.get("email") or "—")
        s_phone = str(student.get("phone") or "—")

        table_data.append([
            Paragraph(str(idx), cell_sno_style),
            Paragraph(s_roll, cell_roll_style),
            Paragraph(s_name, cell_name_style),
            Paragraph(s_batch, cell_batch_style),
            Paragraph(s_email, cell_email_style),
            Paragraph(s_phone, cell_phone_style),
        ])

    # Col widths sum: 12 + 28 + 50 + 30 + 42 + 20 = 182 mm (exact printable width on A4 with 14mm margins)
    student_table = Table(
        table_data,
        colWidths=[12 * mm, 28 * mm, 50 * mm, 30 * mm, 42 * mm, 20 * mm],
        repeatRows=1,
    )
    student_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#475569")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 3),
            ("RIGHTPADDING", (0, 0), (-1, -1), 3),
        ])
    )
    story.append(student_table)

    # Build the document using the NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)
    return buf.getvalue()
